#!/bin/bash

# YuE-exllamav2-UI Installation Script for Fedora/RHEL with SELinux
# Optimized for RTX 5080 16GB VRAM

set -e

echo "=== YuE-exllamav2-UI Installation Script ==="
echo ""

# Get the script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Detect workspace directory - use environment variable or default
WORKSPACE_DIR="${WORKSPACE_DIR:-$HOME/AI/YuE-exllamav2-UI/workspace}"

echo "Project directory: $SCRIPT_DIR"
echo "Workspace directory: $WORKSPACE_DIR"
echo ""

# Create workspace directories
echo "[1/5] Creating workspace directories..."
mkdir -p "$WORKSPACE_DIR/models"
mkdir -p "$WORKSPACE_DIR/outputs"
echo "✓ Directories created"
echo ""

# Set SELinux context for Docker volumes (Fedora/RHEL)
if command -v getenforce &> /dev/null && [ "$(getenforce)" != "Disabled" ]; then
    echo "[2/5] Configuring SELinux permissions for Docker..."

    # Check if we need sudo
    if [ -w "$WORKSPACE_DIR" ]; then
        chcon -Rt svirt_sandbox_file_t "$WORKSPACE_DIR" || {
            echo "⚠️  Warning: chcon failed. Trying with sudo..."
            sudo chcon -Rt svirt_sandbox_file_t "$WORKSPACE_DIR"
        }
    else
        echo "⚠️  Need elevated privileges for chcon..."
        sudo chcon -Rt svirt_sandbox_file_t "$WORKSPACE_DIR"
    fi

    echo "✓ SELinux context set to container_file_t"
    echo ""
else
    echo "[2/5] SELinux not active, skipping..."
    echo ""
fi

# Set proper permissions (777 to allow container to write)
echo "[3/5] Setting directory permissions..."
chmod -R 777 "$WORKSPACE_DIR"
echo "✓ Permissions set (rwxrwxrwx for Docker access)"
echo ""

# Create .env file with workspace path
echo "[4/5] Creating .env configuration..."
cat > "$SCRIPT_DIR/.env" << EOF
# YuE-exllamav2-UI Configuration
# Generated by install.sh

# Workspace directory (absolute path)
WORKSPACE_DIR=$WORKSPACE_DIR

# Model selection for RTX 5080 16GB VRAM
# Options: all_bf16, all_exl2, all, false, or comma-separated list
# Recommended: YuE-s1-7B-anneal-en-cot-exl2-4.0bpw,YuE-s2-1B-general-exl2-6.0bpw,YuE-upsampler
DOWNLOAD_MODELS=YuE-s1-7B-anneal-en-cot-exl2-4.0bpw,YuE-s2-1B-general-exl2-6.0bpw,YuE-upsampler

# Optional: Hugging Face token (leave empty to skip login)
HF_TOKEN=

# GPU Configuration
NVIDIA_VISIBLE_DEVICES=all
EOF

echo "✓ Configuration saved to .env"
echo ""

# Update docker-compose.yml with workspace path
echo "[5/5] Updating docker-compose.yml..."
sed -i "s|/path/to/models|$WORKSPACE_DIR/models|g" "$SCRIPT_DIR/docker-compose.yml" 2>/dev/null || true
sed -i "s|/path/to/outputs|$WORKSPACE_DIR/outputs|g" "$SCRIPT_DIR/docker-compose.yml" 2>/dev/null || true
echo "✓ docker-compose.yml updated"
echo ""

echo "=== Installation Complete! ==="
echo ""
echo "Next steps:"
echo "  1. Review configuration: nano .env"
echo "  2. Start the container: docker-compose up -d"
echo "  3. Monitor logs: docker-compose logs -f"
echo "  4. Access UI: http://localhost:7860"
echo ""
echo "Workspace: $WORKSPACE_DIR"
echo "  - Models will be saved to: $WORKSPACE_DIR/models"
echo "  - Outputs will be saved to: $WORKSPACE_DIR/outputs"
echo ""
